on: [push]

jobs:
  k6_local_test:
    name: k6 local test on macos
    runs-on: macos-11.0

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: install brew
        run: brew install readline xz openssl

      - name: install pyenv
        run: curl https://pyenv.run | bash
      
      - name: install python
        run: export PATH="/Users/runner/.pyenv/bin:$PATH" && eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)" && pyenv install 3.6.12 --patch < <(curl -sSL https://github.com/python/cpython/commit/8ea6353.patch\?full_index\=1)
        
      - name: change shell
        run: pyenv shell 3.6.12
      
      - name: run test
        run: python -c 'import readline'
