on: [push]

jobs:
  k6_local_test:
    name: k6 local test on macos
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: install brew
        run: brew install readline xz openssl

      - name: install pyenv
        run: curl https://pyenv.run | bash
      
      - name: install python
        run: export PATH="/Users/runner/.pyenv/bin:$PATH" && eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)" && pyenv install 3.6.12
        
      - name: run test
        run: export PATH="/Users/runner/.pyenv/bin:$PATH" && eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)" && pyenv shell 3.6.12 && python -c 'import readline'
      
      - name: archive
        run: tar -zcvf /Users/runner/.pyenv.tar /Users/runner/.pyenv 
      
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: .pyenv
          path: /Users/runner/.pyenv.tar
