on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build_python:
    name: Build and Upload
    runs-on: macos-latest
    
    strategy:
      matrix:
        python: [2.7.18, 3.5.10, 3.6.12, 3.7.9, 3.8.6, 3.9.0]

    steps:
      - name: Build and Archive
        run: |
          curl https://pyenv.run | bash
          export PATH="/Users/runner/.pyenv/bin:$PATH" 
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)" 
          pyenv install ${{ matrix.python }}
          cd /Users/runner/.pyenv/versions
          find . -type d -name __pycache__ -exec rm -r {} \+
          tar -zcf python-${{ matrix.python }}.tar ${{ matrix.python }}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: python-${{ matrix.python }}.tar
          path: /Users/runner/.pyenv/versions/python-${{ matrix.python }}.tar
